#!/usr/bin/bash

#D asanataskinit
#D initializes a branch in the project based on the task in asana

WORKSPACE=$(asana-bot ws | percol)
WORKSPACE=$(echo $WORKSPACE | awk '// {print $1}')
SELECTION=$(asana-bot mt -w $WORKSPACE | percol)
TASKID=$(echo $SELECTION | sed 's/https:\/\/app.asana.com\/0\/0\///g' | sed 's/\/f//')
#CTASKDESC=$(echo $SELECTION | awk -F "[()]" '{ print $2 }')
#CTASKDESC=$(printf '%.34s\n' "$CTASKDESC" | tr -d " ")
task-init $TASKID
