#!/usr/bin/bash

google-chrome-stable http://barbukowski.com.br/programacao/ https://pt-br.facebook.com/pg/afterbotafogo/events/?ref=page_internal https://pt-br.facebook.com/pg/calaboucobar/events/?ref=page_internal https://pt-br.facebook.com/pg/casadamatriz/events/?ref=page_internal 
