#!/usr/bin/bash
#D figma
#D open the browser and search in figma 

if [ -z $2 ]; then
  google-chrome-stable https://www.figma.com/files/search/$1
else
  chromeapp https://www.figma.com/files/search/$1
fi
