#!/usr/bin/bash

#D figma2cssopen
#D based on the name of the figmaconfig files choosen by the user opens the 
#D project

cat figmaconfig | awk '/'$1'/ { print $2 }' | xargs -i google-chrome-stable https://www.figma.com/file/{}
