#!/usr/bin/bash
# __  __ _   _ ____ ___ ____ 
# |  \/  | | | / ___|_ _/ ___|
# | |\/| | | | \___ \| | |    
# | |  | | |_| |___) | | |___ 
# |_|  |_|\___/|____/___\____|
 

OPTS=$(ls ~/music | dmenu -i -l 30)
SELECTION=$(cat ~/music/$OPTS | dmenu -i -l 30)
tizonia --spotify-album "$SELECTION"
