#!/usr/bin/bash

____  _   _ ____    ____             __  __       _     _ 
|  _ \| | | |  _ \  / ___|  ___ __ _ / _|/ _| ___ | | __| |
| |_) | |_| | |_) | \___ \ / __/ _` | |_| |_ / _ \| |/ _` |
|  __/|  _  |  __/   ___) | (_| (_| |  _|  _| (_) | | (_| |
|_|   |_| |_|_|     |____/ \___\__,_|_| |_|  \___/|_|\__,_|
 
if [ -z $1 ]; then
  echo "you need to pass the name of the folder"
  exit 0
fi

git clone git@github.com:scotch-io/scotch-box.git $1
cd $1
rm -rf .git/ .gitignore README.md
vagrant up
